//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallDetails
    {
        public int ID { get; set; }
        public Nullable<int> Call { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Saat { get; set; }
    
        public virtual Call Call1 { get; set; }
    }
}
