//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Missions()
        {
            this.MissionDetails = new HashSet<MissionDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Assignor { get; set; }
        public Nullable<int> Responsible { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Stituation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionDetails> MissionDetails { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Personel Personel1 { get; set; }
    }
}
